name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK (Java 17 is required for Gradle 8.x + Android Gradle Plugin 8.x)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Give permission to Gradle Wrapper
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      # 4. Build Debug APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: QuizKioskApp

      # 5. Upload APK as Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QuizKioskApp-debug-apk
          path: QuizKioskApp/app/build/outputs/apk/debug/app-debug.apk
