name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup JDK (Java 17 for Android Gradle Plugin 8+)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Make Gradle Wrapper executable
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Run tests (optional)
      - name: Run unit tests
        run: ./gradlew test
