name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 👇 Use the correct working directory
      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew
        working-directory: QuizKioskApp

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: QuizKioskApp

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QuizKioskApp-debug-apk
          path: QuizKioskApp/app/build/outputs/apk/debug/app-debug.apk
